##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [3.17.1] date: [Wed Nov 30 21:48:52 CST 2022]
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# target
######################################
TARGET = Simple_FreeRTOS


######################################
# building variables
######################################
# debug build?
DEBUG = 1
# optimization
ifeq ($(DEBUG), 1)
OPT = -Og
else
OPT = -Os
endif


#######################################
# paths
#######################################
# Build path
BUILD_DIR = build

######################################
# source
######################################
# C sources
C_SOURCES =  \
Core/Src/main.c \
Core/Src/freertos.c \
Core/Src/stm32f4xx_it.c \
Core/Src/system_stm32f4xx.c \
Core/Src/stm32f4xx_hal_msp.c \
Core/Src/stm32f4xx_hal_timebase_tim.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ramfunc.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_exti.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.c \
Middlewares/FreeRTOS/src/croutine.c \
Middlewares/FreeRTOS/src/event_groups.c \
Middlewares/FreeRTOS/src/list.c \
Middlewares/FreeRTOS/src/queue.c \
Middlewares/FreeRTOS/src/stream_buffer.c \
Middlewares/FreeRTOS/src/tasks.c \
Middlewares/FreeRTOS/src/timers.c \
Middlewares/FreeRTOS/src/portable/MemMang/heap_4.c \
Middlewares/FreeRTOS/src/portable/GCC/ARM_CM4F/port.c \
Middlewares/u8g2/src/u8x8_setup.c \
Middlewares/u8g2/src/u8x8_u8toa.c \
Middlewares/u8g2/src/u8x8_d_ssd1306_96x16.c \
Middlewares/u8g2/src/u8g2_d_memory.c \
Middlewares/u8g2/src/u8g2_selection_list.c \
Middlewares/u8g2/src/u8g2_hvline.c \
Middlewares/u8g2/src/u8x8_d_ssd1306_128x64_noname.c \
Middlewares/u8g2/src/u8x8_message.c \
Middlewares/u8g2/src/u8x8_d_ssd1306_48x64.c \
Middlewares/u8g2/src/u8x8_d_ssd1305.c \
Middlewares/u8g2/src/u8g2_kerning.c \
Middlewares/u8g2/src/u8x8_input_value.c \
Middlewares/u8g2/src/u8x8_d_st7586s_s028hn118a.c \
Middlewares/u8g2/src/u8g2_polygon.c \
Middlewares/u8g2/src/u8x8_d_uc1604.c \
Middlewares/u8g2/src/u8x8_d_ssd1306_128x32.c \
Middlewares/u8g2/src/u8x8_d_ssd1322.c \
Middlewares/u8g2/src/u8x8_d_sbn1661.c \
Middlewares/u8g2/src/u8g2_input_value.c \
Middlewares/u8g2/src/u8x8_8x8.c \
Middlewares/u8g2/src/u8x8_debounce.c \
Middlewares/u8g2/src/u8x8_d_uc1638.c \
Middlewares/u8g2/src/u8g2_setup.c \
Middlewares/u8g2/src/u8x8_d_ist3020.c \
Middlewares/u8g2/src/u8x8_display.c \
Middlewares/u8g2/src/u8x8_d_ssd1317.c \
Middlewares/u8g2/src/u8x8_d_ks0108.c \
Middlewares/u8g2/src/u8g2_box.c \
Middlewares/u8g2/src/u8x8_selection_list.c \
Middlewares/u8g2/src/u8x8_d_ssd1326.c \
Middlewares/u8g2/src/u8x8_d_st75256.c \
Middlewares/u8g2/src/u8x8_d_ssd1309.c \
Middlewares/u8g2/src/u8x8_byte.c \
Middlewares/u8g2/src/u8x8_d_ssd1607_200x200.c \
Middlewares/u8g2/src/u8x8_d_pcd8544_84x48.c \
Middlewares/u8g2/src/u8log.c \
Middlewares/u8g2/src/u8x8_d_sh1107.c \
Middlewares/u8g2/src/u8log_u8x8.c \
Middlewares/u8g2/src/u8g2_message.c \
Middlewares/u8g2/src/u8x8_d_uc1610.c \
Middlewares/u8g2/src/u8x8_d_sh1106_72x40.c \
Middlewares/u8g2/src/u8g2_line.c \
Middlewares/u8g2/src/u8g2_intersection.c \
Middlewares/u8g2/src/u8g2_fonts.c \
Middlewares/u8g2/src/u8x8_d_sh1106_64x32.c \
Middlewares/u8g2/src/u8x8_d_sed1330.c \
Middlewares/u8g2/src/u8x8_d_pcf8814_hx1230.c \
Middlewares/u8g2/src/u8x8_d_il3820_296x128.c \
Middlewares/u8g2/src/u8x8_d_uc1701_dogs102.c \
Middlewares/u8g2/src/u8g2_cleardisplay.c \
Middlewares/u8g2/src/u8x8_d_ssd1325.c \
Middlewares/u8g2/src/u8g2_font.c \
Middlewares/u8g2/src/u8x8_d_uc1601.c \
Middlewares/u8g2/src/u8x8_d_pcf8812.c \
Middlewares/u8g2/src/u8x8_cad.c \
Middlewares/u8g2/src/u8x8_d_uc1611.c \
Middlewares/u8g2/src/u8x8_string.c \
Middlewares/u8g2/src/u8g2_ll_hvline.c \
Middlewares/u8g2/src/u8x8_fonts.c \
Middlewares/u8g2/src/u8x8_d_ld7032_60x32.c \
Middlewares/u8g2/src/u8x8_d_max7219.c \
Middlewares/u8g2/src/u8x8_d_st7588.c \
Middlewares/u8g2/src/u8x8_d_ssd1606_172x72.c \
Middlewares/u8g2/src/u8x8_d_st7586s_erc240160.c \
Middlewares/u8g2/src/u8x8_d_stdio.c \
Middlewares/u8g2/src/u8x8_d_sh1122.c \
Middlewares/u8g2/src/u8log_u8g2.c \
Middlewares/u8g2/src/u8g2_circle.c \
Middlewares/u8g2/src/u8x8_d_ssd1306_64x48.c \
Middlewares/u8g2/src/u8g2_buffer.c \
Middlewares/u8g2/src/u8g2_bitmap.c \
Middlewares/u8g2/src/u8x8_d_lc7981.c \
Middlewares/u8g2/src/u8x8_d_st7920.c \
Middlewares/u8g2/src/u8x8_d_t6963.c \
Middlewares/u8g2/src/u8x8_d_st7567.c \
Middlewares/u8g2/src/u8x8_d_ls013b7dh03.c \
Middlewares/u8g2/src/u8x8_d_ssd1327.c \
Middlewares/u8g2/src/u8x8_d_sh1108.c \
Middlewares/u8g2/src/u8x8_gpio.c \
Middlewares/u8g2/src/u8x8_d_uc1608.c \
Middlewares/u8g2/src/u8x8_d_uc1617.c \
Middlewares/u8g2/src/u8x8_d_ssd1329.c \
Middlewares/u8g2/src/u8x8_d_ssd1306_64x32.c \
Middlewares/u8g2/src/u8g2_d_setup.c \
Middlewares/u8g2/src/u8x8_d_uc1701_mini12864.c \
Middlewares/u8g2/src/u8x8_u16toa.c \
Middlewares/u8g2/src/u8x8_d_a2printer.c \
Middlewares/u8g2/src/u8x8_d_st7565.c \
Middlewares/u8g2/src/u8x8_capture.c \
Middlewares/u8g2/src/u8g2_button.c \

# ASM sources
ASM_SOURCES =  \
startup_stm32f407xx.s


#######################################
# binaries
#######################################
PREFIX = arm-none-eabi-
# The gcc compiler bin path can be either defined in make command via GCC_PATH variable (> make GCC_PATH=xxx)
# either it can be added to the PATH environment variable.
ifdef GCC_PATH
CC = $(GCC_PATH)/$(PREFIX)gcc
AS = $(GCC_PATH)/$(PREFIX)gcc -x assembler-with-cpp
CP = $(GCC_PATH)/$(PREFIX)objcopy
SZ = $(GCC_PATH)/$(PREFIX)size
else
CC = $(PREFIX)gcc
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
SZ = $(PREFIX)size
endif
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S
 
#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m4

# fpu
FPU = -mfpu=fpv4-sp-d16

# float-abi
FLOAT-ABI = -mfloat-abi=hard

# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS = 

# C defines
C_DEFS =  \
-DUSE_HAL_DRIVER \
-DSTM32F407xx


# AS includes
AS_INCLUDES =  \
-ICore\Inc

# C includes
C_INCLUDES =  \
-ICore/Inc \
-IDrivers/STM32F4xx_HAL_Driver/Inc \
-IDrivers/STM32F4xx_HAL_Driver/Inc/Legacy \
-IMiddlewares/FreeRTOS/include \
-IMiddlewares/FreeRTOS/src/portable/GCC/ARM_CM4F \
-IMiddlewares/u8g2/include \
-IDrivers/CMSIS/Device/ST/STM32F4xx/Include \
-IDrivers/CMSIS/Include


# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

CFLAGS = $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections -std=gnu17

ifeq ($(DEBUG), 1)
CFLAGS += -g -gdwarf-2
endif


# Generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"


#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = STM32F407VGTx_FLASH.ld

# libraries
LIBS = -lc -lm -lrdimon 
LIBDIR = 
LDFLAGS = $(MCU) -specs=rdimon.specs -T$(LDSCRIPT) $(LIBDIR) $(LIBS)
LDFLAGS += -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections -Wl,--print-memory-usage

# default action: build all
all: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin


#######################################
# build the application
#######################################
# list of objects
OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
vpath %.c $(sort $(dir $(C_SOURCES)))
# list of ASM program objects
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASM_SOURCES:.s=.o)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))

$(BUILD_DIR)/%.o: %.c Makefile | $(BUILD_DIR) 
	$(CC) -c $(CFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.s Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) Makefile
	$(CC) $(OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@

$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(HEX) $< $@
	
$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(BIN) $< $@	
	
$(BUILD_DIR):
	mkdir $@		

#######################################
# clean up
#######################################
clean:
	-rm -fR $(BUILD_DIR)
  
#######################################
# dependencies
#######################################
-include $(wildcard $(BUILD_DIR)/*.d)

# *** EOF ***